version: 2

submodules:
  include:
    - files

build:
  os: "ubuntu-lts-latest"
  apt_packages:
    - cmake
    - build-essential
    - gcc
    - gfortran
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - viz
        - test
        - docs

formats: []
